### ISSUE TITLE
[Bug]: Wrong env var path separator used in git bash

### ISSUE THREAD

**Issue by erikstantoncarlson** [blurstudio/hab#41]
### Summary

When using Git Bash on Windows, env vars will be separated by colons (Linux) instead of semi-colons (Windows).
I think this changed in version 0.15.0.

### Expected Behavior

The path separator should match the OS.

### Steps to Reproduce Behavior

1. Launch Git Bash on Windows
2. Run `hab env context`
3. Print an env such as `printenv HOUDINI_PACKAGE_DIR`
4. The paths are separated by `:`

### Solution

Using hab in Command Prompt still works as expected, but it's more of a workaround.

### Environment

- Version: 0.15.0
- OS: Windows 10
- Python Version: 3.9

### Additional Context

`$ printenv HOUIDINI_PACKAGE_DIR`
`path1:path2:path3`

**Comment by MHendricks** [comment]
Fixed in hab>=0.16.0
