### ISSUE TITLE
[Request]: Set URI command

### ISSUE THREAD

**Issue by JamesB-Blur** [blurstudio/hab#49]
### Description

We are also going to need to setup a method for someone to just set the url interactively similar to how your prompt currently works. i.e. Hab set URI would always ask you what uri to use but not launch anything aliases, and Treegrunt (Hab) would respect that change.

### Solution

Create code for a new command in cli.py.  The code already exists to save a new `.hab_user_prefs.json` file so it's just should be a matter of setting up a `click.prompt` for user input.  The Treegunt aspect may need more investigation.

**Comment by MHendricks** [comment]
The goal is to allow us to create a desktop shortcut that lets a user set their uri using the user prefs system. This makes it so we can create general alias desktop shortcuts to launch applications like Maya, Houdini, Nuke, Treegrunt(tool launcher internal to Blur).

These shortcuts would not be for a specific version of the application. They would end up running a command like `hab launch - maya` for the Maya shortcut. This would use the last saved uri for the user, and if that has expired, it would ask them for a new uri. The saved uri would define what version of Maya gets launched.

However the user doesn't have a easy way to change the uri when they switch projects. This issue makes it so we can make an additional shortcut that lets the user view and change the current uri when ever they want easily.

All of this is in preparation for adding gui features to hab that will replicate these features if a window manager, but having the cli support is important for when running from a shell.

Also, we should make sure to communicate to the user if the alias is invalid for the current URI when processing.
