### ISSUE TITLE
[Bug]: Setting environment on default hab config results in error

### ISSUE THREAD

**Issue by Ashen-Blur** [blurstudio/hab#55]
### Summary

I tried setting the following json as the default config for hab and it resulted in an error upon setting the hab env.

### Expected Behavior

The environment should have been set without issue, especially if the URI being used was a valid one that did not require falling back to the default one.

### Steps to Reproduce Behavior

Set the provided json as the default config. Try setting the hab env to any URI.

### Environment

- Version: Hab 0.19.0
- OS: Windows

### Additional Context

Error:
```
hab launch <valid uri> houdini
Hab encountered an error:
pyjson5.Json5IllegalCharacter: ("Expected b'hexadecimal character' near 630, found U+0073", {'name': 'default', 'context': [], 'inherits': False, 'distros': ['houdini19.5', 'htoa19.5', 'houdini19.0==19.0.657', 'htoa19.0==6.1.3.1', 'hsite', 'maya2020', 'maya2023', 'animBot', 'AnimSchool', 'brSkinBrush', 'studiolibrary', 'tikal'], 'environment': {'set': {'OCIO': None}}, 'filename': '<path to configs>\\_configs\\default\\default.json'}, 's')
```

Json:
```
{
    "name": "default",
    "context": [],
    "inherits": false,
    "distros": [
        <standard distros for the studio>
    ],
    "environment": {
        "set" : {
            "OCIO": "<path to OCIO config>/config.ocio"
        }
    }
}
```

**Comment by MHendricks** [comment]
This is a problem with the encoding of the json data stored in `"<path to OCIO config>/config.ocio"` It was using backslashes that were not escaped properly, in this case `...s\Useful...` caused the problem and the fix would be `...s\\Useful...` or `...s/Useful...`. In most cases I use forward slashes as hab manages slash direction internally.
